# Generated by Django 5.2.4 on 2025-08-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='nome_completo')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('telefone', models.IntegerField(max_length=9, verbose_name='telefone')),
                ('seu_id_na_provedoraa', models.IntegerField(max_length=8, verbose_name='seu_id_na_provedoraa')),
                ('pin', models.IntegerField(max_length=4, verbose_name='pin')),
            ],
        ),
    ]
