# Generated by Django 5.2.4 on 2025-08-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='pin',
            field=models.IntegerField(verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='seu_id_na_provedoraa',
            field=models.IntegerField(verbose_name='seu_id_na_provedoraa'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='telefone',
            field=models.IntegerField(verbose_name='telefone'),
        ),
    ]
